<?php

namespace Database\Seeders;

// use App\Models\Cit
use App\Models\Cities;
use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    private $state = [
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  // 17
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, // 55
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, // 55
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,  // 55
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, // 214
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 52
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,  // 46
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,  // 37
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,  // 13
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, // 25
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,  // 50
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,   // 22
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,  // 22
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,   // 34
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  // 23
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,  // 31
        12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,   // 17
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,  // 36
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,  // 28
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,  // 21
        16,
        17, 17, 17, 17, 17, 17, 17,    // 7
        18, 18, 18, 18, 18,   // 5
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,      // 14
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,    // 11
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,   // 20
        22, 22, 22, 22, 22, 22,  // 6
        23, 23, 23, 23, 23, 23, 23,  // 7
        24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,   // 16
        25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,   // 17
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,   // 16
        27, 27, 27, 27,   // 4
        28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,  // 24
        29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,  // 11
        30, 30, 30, 30, 30, 30, 30, 30, 30,   // 9
        31,   // 1
        32, // 1
        33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,   // 22
        34, 34, 34, 34, 34, 34, 34, 34,  // 8
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,  // 12
        36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,  // 13
        37, 37, 37, 37, 37, 37, 37, 37, 37, 37,  // 10
        38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,  // 18
        39, 39, 39, 39, 39, 39,  // 6
        40, 40, 40, 40, 40, 40, // 6
        41, 41,  // 2
        42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42,  // 15
        43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,  // 12
        44, 44, 44,  // 3
        45, 45, 45, 45,  // 4
        46, 46, 46, 46, 46,  // 5
        47, 47,  // 2
        48, // 1
        49, 49,  // 1
        50, 50, // 2
        51,
    ];

    private $city = [
        'New York',
        'Buffalo',
        'Rochester',
        'Yonkers',
        'Syracuse',
        'Albany',
        'New Rochelle',
        'Mount Vernon',
        'Schenectady',
        'Utica',
        'White Plains',
        'Hempstead',
        'Troy',
        'Niagara Falls',
        'Binghamton',
        'Freeport',
        'Valley Stream',  // end of 1  #17
        'Los Angeles',
        'San Diego',
        'San Jose',
        'San Francisco',
        'Fresno',
        'Sacramento',
        'Long Beach',
        'Oakland',
        'Bakersfield',
        'Anaheim',
        'Santa Ana',
        'Riverside',
        'Stockton',
        'Chula Vista',
        'Irvine',
        'Fremont',
        'San Bernardino', // 17
        'Modesto',
        'Fontana',
        'Oxnard',
        'Moreno Valley',
        'Huntington Beach',
        'Glendale',
        'Santa Clarita',
        'Garden Grove',
        'Oceanside',
        'Rancho Cucamonga', // 27
        'Santa Rosa',
        'Ontario',
        'Lancaster',
        'Elk Grove',
        'Corona',
        'Palmdale',
        'Salinas',
        'Pomona',
        'Hayward',
        'Escondido', // 37
        'Torrance',
        'Sunnyvale',
        'Orange',
        'Fullerton',
        'Pasadena',
        'Thousand Oaks',
        'Visalia',
        'Simi Valley',
        'Concord',
        'Roseville', // 47
        'Victorville',
        'Santa Clara',
        'Vallejo', // 50
        'Berkeley',
        'El Monte',
        'Downey',
        'Costa Mesa',
        'Inglewood', 'Carlsbad', 'San Buenaventura (Ventura)', 'Fairfield',
        'West Covina', 'Murrieta',  // 60
        'Richmond', 'Norwalk',
        'Antioch', 'Temecula',
        'Burbank', 'Daly City',
        'Rialto', 'Santa Maria',
        'El Cajon', 'San Mateo',    // 70
        'Clovis', 'Compton',
        'Jurupa Valley',
        'Vista',
        'South Gate',
        'Mission Viejo',
        'Vacaville',
        'Carson',
        'Hesperia',  // 80
        'Santa Monica',
        'Westminster',
        'Redding',
        'Santa Barbara',
        'Chico',
        'Newport Beach',
        'San Leandro',
        'San Marcos',
        'Whittier',
        'Hawthorne',  // 90
        'Citrus Heights',
        'Tracy',
        'Alhambra',
        'Livermore',
        'Buena Park',
        'Menifee',
        'Hemet',
        'Lakewood',
        'Merced',
        'Chino',  // 100
        'Indio',
        'Redwood City',
        'Lake Forest',
        'Napa',
        'Tustin',
        'Bellflower',
        'Mountain View',
        'Chino Hills',
        'Baldwin Park',
        'Alameda',  // 110
        'Upland',
        'San Ramon',
        'Folsom',
        'Pleasanton',
        'Union City',
        'Perris',
        'Manteca',
        'Lynwood',
        'Apple Valley',
        'Redlands',  // 120
        'Turlock',
        'Milpitas',
        'Redondo Beach',
        'Rancho Cordova',
        'Yorba Linda',
        'Palo Alto',
        'Davis',
        'Camarillo',
        'Walnut Creek',
        'Pittsburg',  // 130
        'South San Francisco',
        'Yuba City',
        'San Clemente',
        'Laguna Niguel',
        'Pico Rivera',
        'Montebello',
        'Lodi',
        'Madera',
        'Santa Cruz',
        'La Habra',  // 140
        'Encinitas',
        'Monterey Park',
        'Tulare',
        'Cupertino',
        'Gardena',
        'National City',
        'Rocklin',
        'Petaluma',
        'Huntington Park',
        'San Rafael', // 150
        'La Mesa',
        'Arcadia',
        'Fountain Valley',
        'Diamond Bar',
        'Woodland',
        'Santee',
        'Lake Elsinore',
        'Porterville',
        'Paramount',
        'Eastvale',  // 160
        'Rosemead',
        'Hanford',
        'Highland',
        'Brentwood',
        'Novato',
        'Colton',
        'Cathedral City',
        'Delano',
        'Yucaipa',
        'Watsonville',  // 170
        'Placentia',
        'Glendora',
        'Gilroy',
        'Palm Desert',
        'Cerritos',
        'West Sacramento',
        'Aliso Viejo',
        'Poway',
        'La Mirada',
        'Rancho Santa Margarita',  // 180
        'Cypress',
        'Dublin',
        'Covina',
        'Azusa',
        'Palm Springs',
        'San Luis Obispo',
        'Ceres',
        'San Jacinto',
        'Lincoln',
        'Newark',  // 190
        'Lompoc',
        'El Centro',
        'Danville',
        'Bell Gardens',
        'Coachella',
        'Rancho Palos Verdes',
        'San Bruno',
        'Rohnert Park',
        'Brea',
        'La Puente',  // 200
        'Campbell',
        'San Gabriel',
        'Beaumont',
        'Morgan Hill',
        'Culver City',
        'Calexico',
        'Stanton',
        'La Quinta',
        'Pacifica',
        'Montclair',  // 210
        'Oakley',
        'Monrovia',
        'Los Banos',  // 213
        'Martinez', // end of 2  #214
        'Chicago',
        'Aurora',
        'Rockford',
        'Joliet',
        'Naperville',
        'Springfield',
        'Peoria',
        'Elgin',
        'Waukegan',
        'Cicero',
        'Champaign',
        'Bloomington',
        'Arlington Heights',
        'Evanston',
        'Decatur',
        'Schaumburg',
        'Bolingbrook',
        'Palatine',
        'Skokie',
        'Des Plaines', // 20
        'Orland Park',
        'Tinley Park',
        'Oak Lawn',
        'Berwyn',
        'Mount Prospect',
        'Normal',
        'Wheaton',
        'Hoffman Estates',
        'Oak Park',
        'Downers Grove',  // 30
        'Elmhurst',
        'Glenview',
        'DeKalb',
        'Lombard',
        'Belleville',
        'Moline',
        'Buffalo Grove',
        'Bartlett',
        'Urbana',
        'Quincy',  // 40
        'Crystal Lake',
        'Plainfield',
        'Streamwood',
        'Carol Stream',
        'Romeoville',
        'Rock Island',
        'Hanover Park',
        'Carpentersville',
        'Wheeling',
        'Park Ridge',  // 50
        'Addison',
        'Calumet City', // end of 3  #52
        'Houston',
        'San Antonio',
        'Dallas',
        'Austin',
        'Fort Worth',
        'El Paso',
        'Arlington',
        'Corpus Christi',
        'Plano',
        'Laredo', // 10
        'Lubbock',
        'Garland',
        'Irving',
        'Amarillo',
        'Grand Prairie',
        'Brownsville',
        'Pasadena',
        'McKinney',
        'Mesquite',
        'McAllen', // 20
        'Killeen',
        'Frisco',
        'Waco',
        'Carrollton',
        'Denton',
        'Midland',
        'Abilene',
        'Beaumont',
        'Round Rock',
        'Odessa',    // 30
        'Wichita Falls',
        'Richardson',
        'Lewisville',
        'Tyler',
        'College Station',
        'Pearland',
        'San Angelo',
        'Allen',
        'League City',
        'Sugar Land',   // 40
        'Longview',
        'Edinburg',
        'Mission',
        'Bryan',
        'Baytown',
        'Pharr',
        'Temple',
        'Missouri City',
        'Flower Mound',
        'Harlingen',   // 50
        'North Richland Hills',
        'Victoria',
        'Conroe',
        'New Braunfels',
        'Mansfield',
        'Cedar Park',
        'Rowlett',
        'Port Arthur',
        'Euless',
        'Georgetown',   // 60
        'Pflugerville',
        'DeSoto',
        'San Marcos',
        'Grapevine',
        'Bedford',
        'Galveston',
        'Cedar Hill',
        'Texas City',
        'Wylie',
        'Haltom City',  // 70
        'Keller',
        'Coppell',
        'Rockwall',
        'Huntsville',
        'Duncanville',
        'Sherman',
        'The Colony',
        'Burleson',
        'Hurst',
        'Lancaster',     // 80
        'Texarkana',
        'Friendswood',
        'Weslaco',  // end of 4  #83
        'Philadelphia',
        'Pittsburgh',
        'Allentown',
        'Erie',
        'Reading',
        'Scranton',
        'Bethlehem',
        'Lancaster',
        'Harrisburg',
        'Altoona',
        'York',
        'State College',
        'Wilkes-Barre',  // 13  #end of 5
        'Phoenix',
        'Tucson',
        'Mesa',
        'Chandler',
        'Glendale',
        'Scottsdale',
        'Gilbert',
        'Tempe',
        'Peoria',
        'Surprise',  // 10
        'Yuma',
        'Avondale',
        'Goodyear',
        'Flagstaff',
        'Buckeye',
        'Lake Havasu City',
        'Casa Grande',
        'Sierra Vista',
        'Maricopa',
        'Oro Valley',   // 20
        'Prescott',
        'Bullhead City',
        'Prescott Valley',
        'Marana',
        'Apache Junction',  // 25 #end of 6
        'Jacksonville',
        'Miami',
        'Tampa',
        'Orlando',
        'St. Petersburg',
        'Hialeah',
        'Tallahassee',
        'Fort Lauderdale',
        'Port St. Lucie',
        'Cape Coral',  // 10
        'Pembroke Pines',
        'Hollywood',
        'Miramar',
        'Gainesville',
        'Coral Springs',
        'Miami Gardens',
        'Clearwater',
        'Palm Bay',
        'Pompano Beach',
        'West Palm Beach',  // 20
        'Lakeland',
        'Davie',
        'Miami Beach',
        'Sunrise',
        'Plantation',
        'Boca Raton',
        'Deltona',
        'Largo',
        'Deerfield Beach',
        'Palm Coast',  // 30
        'Melbourne',
        'Boynton Beach',
        'Lauderhill',
        'Weston',
        'Fort Myers',
        'Kissimmee',
        'Homestead',
        'Tamarac',
        'Delray Beach',
        'Daytona Beach', // 40
        'North Miami',
        'Wellington',
        'North Port',
        'Jupiter',
        'Ocala',
        'Port Orange',
        'Margate',
        'Coconut Creek',
        'Sanford',
        'Sarasota',   // 50
        'Pensacola',
        'Bradenton',
        'Palm Beach Gardens',
        'Pinellas Park',
        'Coral Gables',
        'Doral',
        'Bonita Springs',
        'Apopka',
        'Titusville',
        'North Miami Beach',  // 60
        'Oakland Park',
        'Fort Pierce',
        'North Lauderdale',
        'Cutler Bay',
        'Altamonte Springs',
        'St. Cloud',
        'Greenacres',
        'Ormond Beach',
        'Ocoee',
        'Hallandale Beach',  // 70
        'Winter Garden',
        'Aventura', // end of 7   #72
        'Indianapolis',
        'Fort Wayne',
        'Evansville',
        'South Bend',
        'Carmel',
        'Bloomington',
        'Fishers',
        'Hammond',
        'Gary',
        'Muncie',   // 10
        'Lafayette',
        'Terre Haute',
        'Kokomo',
        'Anderson',
        'Noblesville',
        'Greenwood',
        'Elkhart',
        'Mishawaka',
        'Lawrence',
        'Jeffersonville',  // 20
        'Columbus',
        'Portage', // end of 8   #22
        'Columbus',
        'Cleveland',
        'Cincinnati',
        'Toledo',
        'Akron',
        'Dayton',
        'Parma',
        'Canton',
        'Youngstown',
        'Lorain',   // 10
        'Hamilton',
        'Springfield',
        'Kettering',
        'Elyria',
        'Lakewood',
        'Cuyahoga Falls',
        'Middletown',
        'Euclid',
        'Newark',
        'Mansfield',   // 20
        'Mentor',
        'Beavercreek',
        'Cleveland Heights',
        'Strongsville',
        'Dublin',
        'Fairfield',
        'Findlay',
        'Warren',
        'Lancaster',
        'Lima',  // 30
        'Huber Heights',
        'Westerville',
        'Marion',
        'Grove City', // end of 9   #34
        'Charlotte',
        'Raleigh',
        'Greensboro',
        'Durham',
        'Winston-Salem',
        'Fayetteville',
        'Cary',
        'Wilmington',
        'High Point',
        'Greenville',  // 10
        'Asheville',
        'Concord',
        'Gastonia',
        'Jacksonville',
        'Chapel Hill',
        'Rocky Mount',
        'Burlington',
        'Wilson',
        'Huntersville',
        'Kannapolis',   // 20
        'Apex',
        'Hickory',
        'Goldsboro', // end of 10  #23
        'Detroit',
        'Grand Rapids',
        'Warren',
        'Sterling Heights',
        'Ann Arbor',
        'Lansing',
        'Flint',
        'Dearborn',
        'Livonia',
        'Westland',  // 10
        'Troy',
        'Farmington Hills',
        'Kalamazoo',
        'Wyoming',
        'Southfield',
        'Rochester Hills',
        'Taylor',
        'Pontiac',
        'St. Clair Shores',
        'Royal Oak',  // 20
        'Novi',
        'Dearborn Heights',
        'Battle Creek',
        'Saginaw',
        'Kentwood',
        'East Lansing',
        'Roseville',
        'Portage',
        'Midland',
        'Lincoln Park',
        'Muskegon', // end of 11  #31
        'Memphis',
        'Nashville-Davidson',
        'Knoxville',
        'Chattanooga',
        'Clarksville',
        'Murfreesboro',
        'Jackson',
        'Franklin',
        'Johnson City',
        'Bartlett',
        'Hendersonville',
        'Kingsport',
        'Collierville',
        'Cleveland',
        'Smyrna',
        'Germantown',
        'Brentwood', // end of 12   #17
        'Boston',
        'Worcester',
        'Springfield',
        'Lowell',
        'Cambridge',
        'New Bedford',
        'Brockton',
        'Quincy',
        'Lynn',
        'Fall River',  // 10
        'Newton',
        'Lawrence',
        'Somerville',
        'Waltham',
        'Haverhill',
        'Malden',
        'Medford',
        'Taunton',
        'Chicopee',
        'Weymouth Town',  // 20
        'Revere',
        'Peabody',
        'Methuen',
        'Barnstable Town',
        'Pittsfield',
        'Attleboro',
        'Everett',
        'Salem',
        'Westfield',
        'Leominster',  // 30
        'Fitchburg',
        'Beverly',
        'Holyoke',
        'Marlborough',
        'Woburn',
        'Chelsea', // end of 13  #36
        'Seattle',
        'Spokane',
        'Tacoma',
        'Vancouver',
        'Bellevue',
        'Kent',
        'Everett',
        'Renton',
        'Yakima',
        'Federal Way',  // 10
        'Spokane Valley',
        'Bellingham',
        'Kennewick',
        'Auburn',
        'Pasco',
        'Marysville',
        'Lakewood',
        'Redmond',
        'Shoreline',
        'Richland',  // 20
        'Kirkland',
        'Burien',
        'Sammamish',
        'Olympia',
        'Lacey',
        'Edmonds',
        'Bremerton',
        'Puyallup', // end of 14  #28
        'Denver',
        'Colorado Springs',
        'Aurora',
        'Fort Collins',
        'Lakewood',
        'Thornton',
        'Arvada',
        'Westminster',
        'Pueblo',
        'Centennial',
        'Boulder',
        'Greeley',
        'Longmont',
        'Loveland',
        'Grand Junction',
        'Broomfield',
        'Castle Rock',
        'Commerce City',
        'Parker',
        'Littleton',
        'Northglenn', // end of 15   #21
        'Washington', // end of 16  #1
        'Baltimore',
        'Frederick',
        'Rockville',
        'Gaithersburg',
        'Bowie',
        'Hagerstown',
        'Annapolis', // end of 17   #7
        'Louisville/Jefferson County',
        'Lexington-Fayette',
        'Bowling Green',
        'Owensboro',
        'Covington', // end of 18 #5
        'Portland',
        'Eugene',
        'Salem',
        'Gresham',
        'Hillsboro',
        'Beaverton',
        'Bend',
        'Medford',
        'Springfield',
        'Corvallis', // 10
        'Albany',
        'Tigard',
        'Lake Oswego',
        'Keizer',   // end of 19  #14
        'Oklahoma City',
        'Tulsa',
        'Norman',
        'Broken Arrow',
        'Lawton',
        'Edmond',
        'Moore',
        'Midwest City',
        'Enid',
        'Stillwater',
        'Muskogee', // end of 20  #11
        'Milwaukee',
        'Madison',
        'Green Bay',
        'Kenosha',
        'Racine',
        'Appleton',
        'Waukesha',
        'Eau Claire',
        'Oshkosh',
        'Janesville',
        'West Allis',
        'La Crosse',
        'Sheboygan',
        'Wauwatosa',
        'Fond du Lac',
        'New Berlin',
        'Wausau',
        'Brookfield',
        'Greenfield',
        'Beloit',   // end of 21  #20
        'Las Vegas',
        'Henderson',
        'Reno',
        'North Las Vegas',
        'Sparks',
        'Carson City', // end of 22  #6
        'Albuquerque',
        'Las Cruces',
        'Rio Rancho',
        'Santa Fe',
        'Roswell',
        'Farmington',
        'Clovis',   // end of 23 #7
        'Kansas City',
        'St. Louis',
        'Springfield',
        'Independence',
        'Columbia',
        "Lee's Summit",
        "O'Fallon",
        'St. Joseph',
        'St. Charles',
        'St. Peters',  // 10
        'Blue Springs',
        'Florissant',
        'Joplin',
        'Chesterfield',
        'Jefferson City',
        'Cape Girardeau',  // end of 24  #16
        'Virginia Beach',
        'Norfolk',
        'Chesapeake',
        'Richmond',
        'Newport News',
        'Alexandria',
        'Hampton',
        'Roanoke',
        'Portsmouth',
        'Suffolk',
        'Lynchburg',
        'Harrisonburg',
        'Leesburg',
        'Charlottesville',
        'Danville',
        'Blacksburg',
        'Manassas',   // end of 25 #17
        'Atlanta',
        'Columbus',
        'Augusta-Richmond County',
        'Savannah',
        'Athens-Clarke County',
        'Sandy Springs',
        'Roswell',
        'Macon',
        'Johns Creek',
        'Albany',
        'Warner Robins',
        'Alpharetta',
        'Marietta',
        'Valdosta',
        'Smyrna',
        'Dunwoody', // end of 26  #16
        'Omaha',
        'Lincoln',
        'Bellevue',
        'Grand Island', // end of 27  #4
        'Minneapolis',
        'St. Paul',
        'Rochester',
        'Duluth',
        'Bloomington',
        'Brooklyn Park',
        'Plymouth',
        'St. Cloud',
        'Eagan',
        'Woodbury',
        'Maple Grove',
        'Eden Prairie',
        'Coon Rapids',
        'Burnsville',
        'Blaine',
        'Lakeville',
        'Minnetonka',
        'Apple Valley',
        'Edina',
        'St. Louis Park',
        'Mankato',
        'Maplewood',
        'Moorhead',
        'Shakopee',  // end of 28 #24
        'Wichita',
        'Overland Park',
        'Kansas City',
        'Olathe',
        'Topeka',
        'Lawrence',
        'Shawnee',
        'Manhattan',
        'Lenexa',
        'Salina',
        'Hutchinson',  // end of 29  #11
        'New Orleans',
        'Baton Rouge',
        'Shreveport',
        'Lafayette',
        'Lake Charles',
        'Kenner',
        'Bossier City',
        'Monroe',
        'Alexandria', // end of 30  #9
        'Honolulu', // end of 31  #1
        'Anchorage', // end of 32 #1
        'Newark',
        'Jersey City',
        'Paterson',
        'Elizabeth',
        'Clifton',
        'Trenton',
        'Camden',
        'Passaic',
        'Union City',
        'Bayonne',
        'East Orange',
        'Vineland',
        'New Brunswick',
        'Hoboken',
        'Perth Amboy',
        'West New York',
        'Plainfield',
        'Hackensack',
        'Sayreville',
        'Kearny',
        'Linden',
        'Atlantic City', // 22 end of 33
        'Boise City',
        'Nampa',
        'Meridian',
        'Idaho Falls',
        'Pocatello',
        'Caldwell',
        "Coeur d'Alene",
        'Twin Falls',  // end of 34   8
        'Birmingham',
        'Montgomery',
        'Mobile',
        'Huntsville',
        'Tuscaloosa',
        'Hoover',
        'Dothan',
        'Auburn',
        'Decatur',
        'Madison',
        'Florence',
        'Gadsden', // end of 35  12
        'Des Moines',
        'Cedar Rapids',
        'Davenport',
        'Sioux City',
        'Iowa City',
        'Waterloo',
        'Council Bluffs',
        'Ames',
        'West Des Moines',
        'Dubuque',
        'Ankeny',
        'Urbandale',
        'Cedar Falls', // end of 36  13
        'Little Rock',
        'Fort Smith',
        'Fayetteville',
        'Springdale',
        'Jonesboro',
        'North Little Rock',
        'Conway',
        'Rogers',
        'Pine Bluff',
        'Bentonville', // end of 37  10
        'Salt Lake City',
        'West Valley City',
        'Provo',
        'West Jordan',
        'Orem',
        'Sandy',
        'Ogden',
        'St. George',
        'Layton',
        'Taylorsville',
        'South Jordan',
        'Lehi',
        'Logan',
        'Murray',
        'Draper',
        'Bountiful',
        'Riverton',
        'Roy',  // end of 38  18
        'Providence',
        'Warwick',
        'Cranston',
        'Pawtucket',
        'East Providence',
        'Woonsocket', // end of 39 #6
        'Jackson',
        'Gulfport',
        'Southaven',
        'Hattiesburg',
        'Biloxi',
        'Meridian', // end of 40  #6
        'Sioux Falls',
        'Rapid City',  // end of 41 #2
        'Bridgeport',
        'New Haven',
        'Stamford',
        'Hartford',
        'Waterbury',
        'Norwalk',
        'Danbury',
        'New Britain',
        'Meriden',
        'Bristol',
        'West Haven',
        'Milford',
        'Middletown',
        'Norwich',
        'Shelton', // end of 42 15
        'Columbia',
        'Charleston',
        'North Charleston',
        'Mount Pleasant',
        'Rock Hill',
        'Greenville',
        'Summerville',
        'Sumter',
        'Goose Creek',
        'Hilton Head Island',
        'Florence',
        'Spartanburg', // end of 43 12
        'Manchester',
        'Nashua',
        'Concord', // end of 44 #3
        'Fargo',
        'Bismarck',
        'Grand Forks',
        'Minot', // end of 45 #4
        'Billings',
        'Missoula',
        'Great Falls',
        'Bozeman',
        'Kalispell', // end of 46 5
        'Wilmington',
        'Dover', // end of 47 2
        'Portland', // end of 48 1
        'Cheyenne',
        'Casper', // end of 49 2
        'Charleston',
        'Huntington', // end of 50 2
        'Burlington', // end of 51 1
    ];

    public function run(): void
    {
        foreach (range(1, count($this->city)) as $index) {
            Cities::create([
                'name' => $this->city[$index - 1],
                'state_id' => $this->state[$index - 1],
            ]);

        }
    }
}
