<?php

return [
    [
        'type' => 'live',
        'serverName' => 'flex',
        'branchName' => 'flex-frontend-prod',
        'backendBranchName' => 'flex-backend-prod',
    ],
    [
        'type' => 'live',
        'serverName' => 'soar',
        'branchName' => 'soar-frontend',
        'backendBranchName' => 'soar-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'aveyo',
        'branchName' => 'aveyo-frontend-prod',
        'backendBranchName' => 'aveyo-backend-prod',
    ],
    [
        'type' => 'live',
        'serverName' => 'aveyo2',
        'branchName' => 'aveyo2.frontend-prod',
        'backendBranchName' => 'aveyo2-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'vantagepoint',
        'branchName' => 'vantagepoint-frontend',
        'backendBranchName' => 'vantagepoint-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'harvestsolar',
        'branchName' => 'harvestsolar-frontend',
        'backendBranchName' => 'harvestsolar-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'simpleflow',
        'branchName' => 'simpleflow-frontend',
        'backendBranchName' => 'simpleflow-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'groffs',
        'branchName' => 'groffs-frontend',
        'backendBranchName' => 'groffs-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'toptier',
        'branchName' => 'toptier-frontend',
        'backendBranchName' => 'toptier-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'maine',
        'branchName' => 'frontend-maine',
        'backendBranchName' => 'backend-maine',
    ],
    [
        'type' => 'live',
        'serverName' => 'capecod',
        'branchName' => 'capecode-frontend',
        'backendBranchName' => 'capecode-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'flexpest',
        'branchName' => 'flexpest-frontend',
        'backendBranchName' => 'flexpest-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'momentum',
        'branchName' => 'momentum-frontend',
        'backendBranchName' => 'momentum-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'homeguard',
        'branchName' => 'homeguard-frontend',
        'backendBranchName' => 'homeguard-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'threeriverspest',
        'branchName' => 'threeriverspest-frontend',
        'backendBranchName' => 'threeriverspest-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'frdmturf',
        'branchName' => 'frdmturf-frontend',
        'backendBranchName' => 'frdmturf-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'currentenergy',
        'branchName' => 'currentenergy-frontend',
        'backendBranchName' => 'currentenergy-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'milestone',
        'branchName' => 'milestone-frontend',
        'backendBranchName' => 'milestone-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'evopest',
        'branchName' => 'evopest-frontend',
        'backendBranchName' => 'evopest-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'hawx',
        'branchName' => 'hawx-frontend',
        'backendBranchName' => 'hawx-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'mortgage',
        'branchName' => 'mortgage-frontend',
        'backendBranchName' => 'mortgage-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'adam',
        'branchName' => 'adam-frontend',
        'backendBranchName' => 'adam-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'flextest',
        'branchName' => 'flextest-frontend',
        'backendBranchName' => 'flextest-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'sequifi',
        'branchName' => 'sequifi-frontend',
        'backendBranchName' => 'sequifi-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'testaveyo',
        'branchName' => 'test-aveyo-frontend',
        'backendBranchName' => 'test-aveyo-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'pestdev',
        'branchName' => 'pestdev-frontend',
        'backendBranchName' => 'pestdev-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'pest',
        'branchName' => 'pest-sequifi-frontend',
        'backendBranchName' => 'pest-sequifi-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'uat',
        'branchName' => 'uat-frontend',
        'backendBranchName' => 'uat-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'preprod',
        'branchName' => 'preprod-frontend',
        'backendBranchName' => 'preprod-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'sdev',
        'branchName' => 'sDev-frontend',
        'backendBranchName' => 'sDev-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'solardemo',
        'branchName' => 'solardemo-frontend',
        'backendBranchName' => 'solardemo-backend',
    ],
    [
        'type' => 'live',
        'serverName' => 'turf',
        'branchName' => 'turf-frontend',
        'backendBranchName' => 'turf-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'sstage',
        'branchName' => 'sStage-frontend',
        'backendBranchName' => 'sStage-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'pdev',
        'branchName' => 'pDev-frontend',
        'backendBranchName' => 'pDev-backend',
    ],
    [
        'type' => 'test',
        'serverName' => 'pstage',
        'branchName' => 'pStage-frontend',
        'backendBranchName' => 'pStage-backend',
    ],
];
