<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LegacyApiRawDataHistoryLog extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'legacy_api_raw_data_histories_log';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'legacy_id',
        'pid',
        'weekly_sheet_id',
        'install_partner',
        'install_partner_id',
        'customer_name',
        'customer_address',
        'customer_address_2',
        'customer_city',
        'customer_state',
        'location_code',
        'customer_zip',
        'customer_email',
        'customer_phone',
        'homeowner_id',
        'proposal_id',
        'setter_id',
        'sales_rep_name',
        'employee_id',
        'customer_id',
        'initialAppointmentID',
        'soldBy',
        'soldBy2',
        'initialStatusText',
        'sales_rep_email',
        'kw',
        'balance_age',
        'date_cancelled',
        'customer_signoff',
        'm1_date',
        'm2_date',
        'product',
        'product_id',
        'product_code',
        'sale_product_name',
        'gross_account_value',
        'epc',
        'net_epc',
        'dealer_fee_percentage',
        'dealer_fee_amount',
        'adders',
        'adders_description',
        'redline',
        'total_amount_for_acct',
        'prev_amount_paid',
        'last_date_pd',
        'm1_amount',
        'm2_amount',
        'prev_deducted_amount',
        'cancel_fee',
        'cancel_deduction',
        'lead_cost_amount',
        'adv_pay_back_amount',
        'total_amount_in_period',
        'funding_source',
        'financing_rate',
        'financing_term',
        'scheduled_install',
        'install_complete_date',
        'return_sales_date',
        'cash_amount',
        'loan_amount',
        'closer1_id',
        'closer2_id',
        'setter1_id',
        'setter2_id',
        'closer1_m1',
        'closer2_m1',
        'setter1_m1',
        'setter2_m1',
        'closer1_m2',
        'closer2_m2',
        'setter1_m2',
        'setter2_m2',
        'closer1_commission',
        'closer2_commission',
        'setter1_commission',
        'setter2_commission',
        'closer1_m1_paid_status',
        'closer2_m1_paid_status',
        'setter1_m1_paid_status',
        'setter2_m1_paid_status',
        'closer1_m2_paid_status',
        'closer2_m2_paid_status',
        'setter1_m2_paid_status',
        'setter2_m2_paid_status',
        'closer1_m1_paid_date',
        'closer2_m1_paid_date',
        'setter1_m1_paid_date',
        'setter2_m1_paid_date',
        'closer1_m2_paid_date',
        'closer2_m2_paid_date',
        'setter1_m2_paid_date',
        'setter2_m2_paid_date',
        'mark_account_status_id',
        'pid_status',
        'length_of_agreement',
        'service_schedule',
        'initial_service_cost',
        'auto_pay',
        'card_on_file',
        'subscription_payment',
        'service_completed',
        'last_service_date',
        'initial_service_date',
        'bill_status',
        'data_source_type',
        'source_created_at',
        'source_updated_at',
        'pay_period_from',
        'pay_period_to',
        'import_to_sales',
        'import_status_reason',
        'import_status_description',
        'excel_import_id',
        'contract_sign_date',
        'job_status',
        'trigger_date',
        'customer_payment_json',
    ];
}
